server:
  port: 8888

spring:
  application:
    name: itoken-config
  boot:
    admin:
      client:
        url: http://localhost:8084
  cloud:
    config:
      label: master
      server:
        git:
          uri: git@github.com:tytytytytytytyt/itoken.git
          search-paths: config/respo
          username: 778450868.qq.com
          password: cailing1016
  zipkin:
    base-url: http://localhost:9411


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info