spring:
  application:
    name: itoken-admin
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        service-base-url: http://localhost:8084

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info