spring:
  application:
    name: itoken-zuul
  boot:
    admin:
      client:
        url: http://localhost:9412
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info